package application

// Code generated by jsonapi. DO NOT EDIT.
// Source: github.com/pentops/o5-aws-tool/libo5/o5/application/v1/application

import ()

// WorkerConfig Proto: o5.application.v1.WorkerConfig
type WorkerConfig struct {
	ReplayChance     int64 `json:"replayChance,omitempty"`
	DeadletterChance int64 `json:"deadletterChance,omitempty"`
	NoDeadletters    bool  `json:"noDeadletters"`
}

// DeploymentConfig Proto: o5.application.v1.DeploymentConfig
type DeploymentConfig struct {
	QuickMode bool `json:"quickMode"`
}

// Database_Postgres Proto: o5.application.v1.Database.Postgres
type Database_Postgres struct {
	DbName           string     `json:"dbName,omitempty"`
	ServerGroup      string     `json:"serverGroup,omitempty"`
	DbExtensions     []string   `json:"dbExtensions,omitempty"`
	MigrateContainer *Container `json:"migrateContainer,omitempty"`
	RunOutbox        bool       `json:"runOutbox"`
}

// BlobstoreEnvVar Proto: o5.application.v1.BlobstoreEnvVar
type BlobstoreEnvVar struct {
	Name     string  `json:"name,omitempty"`
	SubPath  *string `json:"subPath,omitempty"`
	S3Direct bool    `json:"s3Direct"`
}

// FromEnvVar Proto: o5.application.v1.FromEnvVar
type FromEnvVar struct {
	Name string `json:"name,omitempty"`
}

// Runtime Proto: o5.application.v1.Runtime
type Runtime struct {
	Name                       string          `json:"name,omitempty"`
	DirectIngress              bool            `json:"directIngress"`
	Containers                 []*Container    `json:"containers,omitempty"`
	Routes                     []*Route        `json:"routes,omitempty"`
	Subscriptions              []*Subscription `json:"subscriptions,omitempty"`
	GrantMetaDeployPermissions bool            `json:"grantMetaDeployPermissions"`
	WorkerConfig               *WorkerConfig   `json:"workerConfig,omitempty"`
}

// AWSConfig_SES Proto: o5.application.v1.AWSConfig.SES
type AWSConfig_SES struct {
	SendEmail bool `json:"sendEmail"`
}

// AWSConfig_SQSPublishAnywhere Proto: o5.application.v1.AWSConfig.SQSPublishAnywhere
type AWSConfig_SQSPublishAnywhere struct {
	SendAnywhere bool `json:"sendAnywhere"`
}

// Blobstore Proto: o5.application.v1.Blobstore
type Blobstore struct {
	Name   string        `json:"name,omitempty"`
	Grants []*Grant      `json:"grants,omitempty"`
	Ref    *BlobstoreRef `json:"ref,omitempty"`
}

// Database Proto: o5.application.v1.Database
type Database struct {
	Name     string             `json:"name,omitempty"`
	Postgres *Database_Postgres `json:"postgres,omitempty"`
}

// DatabaseEnvVar Proto: o5.application.v1.DatabaseEnvVar
type DatabaseEnvVar struct {
	DatabaseName string `json:"databaseName,omitempty"`
}

// Subscription Proto: o5.application.v1.Subscription
type Subscription struct {
	Name            string  `json:"name,omitempty"`
	EnvName         *string `json:"envName,omitempty"`
	TargetContainer string  `json:"targetContainer,omitempty"`
	Port            int64   `json:"port,omitempty"`
	GrpcMethod      *string `json:"grpcMethod,omitempty"`
	ReplyTo         *string `json:"replyTo,omitempty"`
	RawMessage      bool    `json:"rawMessage"`
	MetaInfraEvents bool    `json:"metaInfraEvents"`
}

// Target Proto: o5.application.v1.Target
type Target struct {
	Name string `json:"name,omitempty"`
}

// Grant Proto: o5.application.v1.Grant
type Grant struct {
	Principal string `json:"principal,omitempty"`
}

// Container Proto: o5.application.v1.Container
type Container struct {
	Name              string                 `json:"name,omitempty"`
	ImageUrl          string                 `json:"imageUrl,omitempty"`
	Image             *Container_Image       `json:"image,omitempty"`
	Command           []string               `json:"command,omitempty"`
	Demand            string                 `json:"demand,omitempty"`
	EnvVars           []*EnvironmentVariable `json:"envVars,omitempty"`
	MountDockerSocket bool                   `json:"mountDockerSocket"`
}

// MapEnvVar Proto: o5.application.v1.MapEnvVar
type MapEnvVar struct {
}

// SecretEnvVar Proto: o5.application.v1.SecretEnvVar
type SecretEnvVar struct {
	SecretName string `json:"secretName,omitempty"`
	JsonKey    string `json:"jsonKey,omitempty"`
}

// Route Proto: o5.application.v1.Route
type Route struct {
	Prefix          string   `json:"prefix,omitempty"`
	Subdomains      []string `json:"subdomains,omitempty"`
	Protocol        string   `json:"protocol,omitempty"`
	TargetContainer string   `json:"targetContainer,omitempty"`
	BypassIngress   bool     `json:"bypassIngress"`
	Port            int64    `json:"port,omitempty"`
	RouteGroup      string   `json:"routeGroup,omitempty"`
}

// Secret Proto: o5.application.v1.Secret
type Secret struct {
	Name string `json:"name,omitempty"`
}

// AWSConfig Proto: o5.application.v1.AWSConfig
type AWSConfig struct {
	Ses                *AWSConfig_SES                `json:"ses,omitempty"`
	SqsPublishAnywhere *AWSConfig_SQSPublishAnywhere `json:"sqsPublishAnywhere,omitempty"`
}

// Application Proto: o5.application.v1.Application
type Application struct {
	Name             string            `json:"name,omitempty"`
	Targets          []*Target         `json:"targets,omitempty"`
	Blobstores       []*Blobstore      `json:"blobstores,omitempty"`
	Databases        []*Database       `json:"databases,omitempty"`
	Runtimes         []*Runtime        `json:"runtimes,omitempty"`
	Secrets          []*Secret         `json:"secrets,omitempty"`
	DeploymentConfig *DeploymentConfig `json:"deploymentConfig,omitempty"`
	AwsConfig        *AWSConfig        `json:"awsConfig,omitempty"`
}

// BlobstoreRef Proto: o5.application.v1.BlobstoreRef
type BlobstoreRef struct {
	ReadPermission  bool   `json:"readPermission"`
	WritePermission bool   `json:"writePermission"`
	Application     string `json:"application,omitempty"`
	BucketName      string `json:"bucketName,omitempty"`
}

// Container_Image Proto: o5.application.v1.Container.Image
type Container_Image struct {
	Name     string  `json:"name,omitempty"`
	Tag      *string `json:"tag,omitempty"`
	Registry *string `json:"registry,omitempty"`
}

// EnvironmentVariable Proto: o5.application.v1.EnvironmentVariable
type EnvironmentVariable struct {
	Name      string           `json:"name,omitempty"`
	Value     string           `json:"value,omitempty"`
	Database  *DatabaseEnvVar  `json:"database,omitempty"`
	Blobstore *BlobstoreEnvVar `json:"blobstore,omitempty"`
	EnvMap    *MapEnvVar       `json:"envMap,omitempty"`
	FromEnv   *FromEnvVar      `json:"fromEnv,omitempty"`
	Secret    *SecretEnvVar    `json:"secret,omitempty"`
	O5        string           `json:"o5,omitempty"`
}
