package client

// Code generated by jsonapi. DO NOT EDIT.
// Source: github.com/pentops/o5-aws-tool/libo5/j5/client/v1/client

import (
	auth "github.com/pentops/o5-aws-tool/libo5/j5/auth/v1/auth"
	schema "github.com/pentops/o5-aws-tool/libo5/j5/schema/v1/schema"
	time "time"
)

// Metadata Proto: Metadata
type Metadata struct {
	BuiltAt *time.Time `json:"builtAt,omitempty"`
}

// ListRequest Proto: ListRequest
type ListRequest struct {
	SearchableFields []*ListRequest_SearchField `json:"searchableFields,omitempty"`
	SortableFields   []*ListRequest_SortField   `json:"sortableFields,omitempty"`
	FilterableFields []*ListRequest_FilterField `json:"filterableFields,omitempty"`
}

// Service Proto: Service
type Service struct {
	Name    string    `json:"name,omitempty"`
	Methods []*Method `json:"methods,omitempty"`
}

// API Proto: API
type API struct {
	Packages []*Package `json:"packages,omitempty"`
	Metadata *Metadata  `json:"metadata,omitempty"`
}

// StateEvent Proto: StateEvent
type StateEvent struct {
	Name        string `json:"name,omitempty"`
	FullName    string `json:"fullName"`
	Description string `json:"description,omitempty"`
}

// Method_Request Proto: Method_Request
type Method_Request struct {
	Body            *schema.Object           `json:"body,omitempty"`
	PathParameters  []*schema.ObjectProperty `json:"pathParameters,omitempty"`
	QueryParameters []*schema.ObjectProperty `json:"queryParameters,omitempty"`
	List            *ListRequest             `json:"list,omitempty"`
}

// ListRequest_SortField Proto: ListRequest_SortField
type ListRequest_SortField struct {
	Name        string  `json:"name,omitempty"`
	DefaultSort *string `json:"defaultSort,omitempty"`
}

// ListRequest_FilterField Proto: ListRequest_FilterField
type ListRequest_FilterField struct {
	Name           string   `json:"name,omitempty"`
	DefaultFilters []string `json:"defaultFilters,omitempty"`
}

// Package Proto: Package
type Package struct {
	Label         string                `json:"label,omitempty"`
	Name          string                `json:"name,omitempty"`
	Prose         string                `json:"prose,omitempty"`
	Services      []*Service            `json:"services,omitempty"`
	StateEntities []*StateEntity        `json:"stateEntities,omitempty"`
	Schemas       map[string]RootSchema `json:"schemas,omitempty"`
}

// Method Proto: Method
type Method struct {
	Name         string               `json:"name,omitempty"`
	FullGrpcName string               `json:"fullGrpcName,omitempty"`
	HttpMethod   string               `json:"httpMethod,omitempty"`
	HttpPath     string               `json:"httpPath,omitempty"`
	Request      *Method_Request      `json:"request"`
	ResponseBody *schema.Object       `json:"responseBody"`
	Auth         *auth.MethodAuthType `json:"auth,omitempty"`
}

// StateEntity Proto: StateEntity
type StateEntity struct {
	Name            string        `json:"name,omitempty"`
	FullName        string        `json:"fullName"`
	SchemaName      string        `json:"schemaName"`
	Overview        string        `json:"overview,omitempty"`
	PrimaryKey      []string      `json:"primaryKey,omitempty"`
	QueryService    *Service      `json:"queryService,omitempty"`
	CommandServices []*Service    `json:"commandServices,omitempty"`
	Events          []*StateEvent `json:"events,omitempty"`
}

// ListRequest_SearchField Proto: ListRequest_SearchField
type ListRequest_SearchField struct {
	Name string `json:"name,omitempty"`
}
