package list

// Code generated by jsonapi. DO NOT EDIT.
// Source: github.com/pentops/o5-aws-tool/libo5/j5/list/v1/list

import ()

// SearchingConstraint Proto: SearchingConstraint
type SearchingConstraint struct {
	Searchable      bool   `json:"searchable"`
	FieldIdentifier string `json:"fieldIdentifier,omitempty"`
}

// Or Proto: Or
type Or struct {
	Filters []*Filter `json:"filters,omitempty"`
}

// EnumRules Proto: EnumRules
type EnumRules struct {
	Filtering *FilteringConstraint `json:"filtering,omitempty"`
}

// Sort Proto: Sort
type Sort struct {
	Field      string `json:"field,omitempty"`
	Descending bool   `json:"descending"`
}

// OpenTextRules Proto: OpenTextRules
type OpenTextRules struct {
	Searching *SearchingConstraint `json:"searching,omitempty"`
}

// Field Proto: Field
type Field struct {
	Name string      `json:"name,omitempty"`
	Type *Field_Type `json:"type,omitempty"`
}

// TimestampRules Proto: TimestampRules
type TimestampRules struct {
	Filtering *FilteringConstraint `json:"filtering,omitempty"`
	Sorting   *SortingConstraint   `json:"sorting,omitempty"`
}

// Filter Proto Message: Filter
type Filter struct {
	J5TypeKey string `json:"!type,omitempty"`
	Field     *Field `json:"field,omitempty"`
	And       *And   `json:"and,omitempty"`
	Or        *Or    `json:"or,omitempty"`
}

func (s Filter) OneofKey() string {
	if s.Field != nil {
		return "field"
	}
	if s.And != nil {
		return "and"
	}
	if s.Or != nil {
		return "or"
	}
	return ""
}

func (s Filter) Type() interface{} {
	if s.Field != nil {
		return s.Field
	}
	if s.And != nil {
		return s.And
	}
	if s.Or != nil {
		return s.Or
	}
	return nil
}

// FilteringConstraint Proto: FilteringConstraint
type FilteringConstraint struct {
	Filterable     bool     `json:"filterable"`
	DefaultFilters []string `json:"defaultFilters,omitempty"`
}

// KeyRules Proto: KeyRules
type KeyRules struct {
	Filtering *FilteringConstraint `json:"filtering,omitempty"`
}

// Range Proto: Range
type Range struct {
	Min string `json:"min,omitempty"`
	Max string `json:"max,omitempty"`
}

// BooleanRules Proto: BooleanRules
type BooleanRules struct {
	Filtering *FilteringConstraint `json:"filtering,omitempty"`
}

// Search Proto: Search
type Search struct {
	Field string `json:"field,omitempty"`
	Value string `json:"value,omitempty"`
}

// SortingConstraint Proto: SortingConstraint
type SortingConstraint struct {
	Sortable    bool `json:"sortable"`
	DefaultSort bool `json:"defaultSort"`
}

// IntegerRules Proto: IntegerRules
type IntegerRules struct {
	Filtering *FilteringConstraint `json:"filtering,omitempty"`
	Sorting   *SortingConstraint   `json:"sorting,omitempty"`
}

// And Proto: And
type And struct {
	Filters []*Filter `json:"filters,omitempty"`
}

// PageRequest Proto: PageRequest
type PageRequest struct {
	Token    *string `json:"token,omitempty"`
	PageSize *int64  `json:"pageSize,omitempty"`
}

// Field_Type Proto Message: Field_type
type Field_Type struct {
	J5TypeKey string  `json:"!type,omitempty"`
	Value     *string `json:"value,omitempty"`
	Range     *Range  `json:"range,omitempty"`
}

func (s Field_Type) OneofKey() string {
	if s.Value != nil {
		return "value"
	}
	if s.Range != nil {
		return "range"
	}
	return ""
}

func (s Field_Type) Type() interface{} {
	if s.Value != nil {
		return s.Value
	}
	if s.Range != nil {
		return s.Range
	}
	return nil
}

// FloatRules Proto: FloatRules
type FloatRules struct {
	Filtering *FilteringConstraint `json:"filtering,omitempty"`
	Sorting   *SortingConstraint   `json:"sorting,omitempty"`
}

// QueryRequest Proto: QueryRequest
type QueryRequest struct {
	Searches []*Search `json:"searches,omitempty"`
	Sorts    []*Sort   `json:"sorts,omitempty"`
	Filters  []*Filter `json:"filters,omitempty"`
}

// OneofRules Proto: OneofRules
type OneofRules struct {
	Filtering *FilteringConstraint `json:"filtering,omitempty"`
}

// PageResponse Proto: PageResponse
type PageResponse struct {
	NextToken *string `json:"nextToken,omitempty"`
}
